<a href="https://colab.research.google.com/github/rijosasidharlearning-jpg/DataScienceLab1/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy


#1 Dimensional numpy arrays Or Vectors

In [3]:
import numpy as np;

#create 1 D array from list
mylist =[1,2,3,4 ]
arr1 =np.array(mylist)
print(arr1)

[1 2 3 4]


In [2]:
#create 1 D array from tuple
tuple1 = (1,2,3,4)
arr2 = np.array(tuple1)
print(arr2)

[1 2 3 4]


In [3]:
#create 1 D array from set

set1 = {1,2,3,4}
arr3 = np.array(set1)
print(arr3)

{1, 2, 3, 4}


In [4]:
print(type(arr1),type(arr2),type(arr3) )

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [5]:
print(arr1[0],arr2[0])

1 1


In [6]:
print(arr3[0])

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

#homogeneous checks

In [12]:
#create a numpy array with mixd types // converts all elements to higer datatype present in the list
mixedlst= [2,3,5.6,8,10,3.4,9j]
arr4 = np.array(mixedlst)
print(arr4)
print(type(arr4[0]))

[ 2. +0.j  3. +0.j  5.6+0.j  8. +0.j 10. +0.j  3.4+0.j  0. +9.j]
<class 'numpy.complex128'>


In [13]:
mixedlst1= [2,3,5.6,8,10,3.4,9]
arr5 = np.array(mixedlst1)
print(arr5)
print(type(arr5[0]))

[ 2.   3.   5.6  8.  10.   3.4  9. ]
<class 'numpy.float64'>


In [15]:
mixedlst2= [2,3,5.6,8,10,3.4,9j,"101"]
arr6 = np.array(mixedlst2)
print(arr6)
print(type(arr6[0]))

['2' '3' '5.6' '8' '10' '3.4' '9j' '101']
<class 'numpy.str_'>


#2 Dimenional numpy arrays or Matrices

In [4]:
matarr1 = np.array([[1,2],[3,4]])
print(matarr1)

[[1 2]
 [3 4]]


In [5]:
matarr1 = np.array([[1,2,3],[3,4,4]])
print(matarr1)

[[1 2 3]
 [3 4 4]]


In [6]:
# builtin functions
#vectors
z1 =  np.ones(5)
print (z1)

[1. 1. 1. 1. 1.]


In [7]:
z2= z1.astype(int)
print(z2)


[1 1 1 1 1]


In [8]:
#matrices

z3 = np.ones((2,3))
print(z3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
z4= np.zeros((4,5))
print(z4.astype(int))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [10]:
z5 = np.zeros((2,3,4))
print(z5)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


##np.arange()

In [27]:
a1= np.arange(10)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
a2 = np.arange(2,12)
print(a2)

[ 2  3  4  5  6  7  8  9 10 11]


In [29]:
a3= np.arange(2,20,2)
print(a3)

[ 2  4  6  8 10 12 14 16 18]


#Attributes of numpy arrays - shape,ndim,size,dtype

In [11]:
print (z5)
print (z2)
print (z3)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[1 1 1 1 1]
[[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
print(z2.size,z2.shape,z2.ndim,z2.dtype)

5 (5,) 1 int64


In [36]:
print(z3.size,z3.shape,z3.ndim,z3.dtype)

6 (2, 3) 2 float64


In [37]:
print(z5.size,z5.shape,z5.ndim,z5.dtype)

24 (2, 3, 4) 3 float64


##Slicing

In [23]:
sarr1 =np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(sarr1)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [9]:
sarr1[0::1,2:4:1]

array([[3, 4],
       [8, 9]])

## Copy

In [24]:
carr1=sarr1
print(carr1)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [25]:
carr2= np.copy(carr1)
print(carr2)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [26]:
sarr1 = np.arange(10,20,2)
print(sarr1)

[10 12 14 16 18]


In [27]:
print(carr2)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [28]:
print(carr1)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [29]:
print(sarr1)

[10 12 14 16 18]


In [41]:
samplearr = np.array([12,23,234,23,54,656])
sample2 = np.insert(samplearr ,2,99 )
print(sample2)

[ 12  23  99 234  23  54 656]


## np.linspace Divides equally the given space for the no fof point sgiven

In [43]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

##Type conversions in Numpy Arrays

In [45]:
converArr = [12,4,5,6]
npconarr = np.asarray(converArr)
print(npconarr, type(npconarr))

[12  4  5  6] <class 'numpy.ndarray'>


In [53]:
#reshape
samp2 =  np.ones(9).astype(int)
print(samp2)
reshaped =samp2.reshape((3,3))
print(reshaped)

[1 1 1 1 1 1 1 1 1]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [54]:
reshaped.ravel()

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

# Data Optimization


In [15]:
opt1 =  np.array([1,2,4,5,77,8,99,])
print(type(opt1),opt1.dtype)
opt2= np.array([1,2,4,5,77,8,99,],dtype= np.int8)
print(type(opt2),opt2.dtype)

<class 'numpy.ndarray'> int64
<class 'numpy.ndarray'> int8


#Vector Operations


In [17]:
v1 = np.array([1,2,3,4])
v2= np.array([3,4,5,6])
print("Sum " , v1+v2)
print("Subtraction " , v1-v2)
print("Multiplication " , v1*v2)
print("Divison ",v2/v1)
print("Scalar ",2*v1)
print("comaprison " , v1>v2)
print("comaprison " , v2>=v1)

Sum  [ 4  6  8 10]
Subtraction  [-2 -2 -2 -2]
Multiplication  [ 3  8 15 24]
Divison  [3.         2.         1.66666667 1.5       ]
Scalar  [2 4 6 8]
comaprison  [False False False False]
comaprison  [ True  True  True  True]


In [26]:
#Magnitude of vector
print(np.linalg.norm(v1))
print(np.linalg.norm(v2))

5.477225575051661
9.273618495495704


##Metrices

In [24]:
m1 = np.array([[1,2,3,4],[3,4,5,6]])
m2 = np.array([[2,2,2,2],[3,3,3,3],[1,1,1,1],[4,4,4,4]]) #no of columns in first matrix should match no of  rows in second matrix

print("dot product" , np.dot(m1,m2), " or ", m1 @ m2)

dot product [[27 27 27 27]
 [47 47 47 47]]  or  [[27 27 27 27]
 [47 47 47 47]]


#Mathematical operations

In [27]:
abs(-100)

100

In [28]:
min(1,2,5,3,66,834,3)

1

In [30]:
sum([1,5,8,4,34])

52

In [31]:
round(1.5)

2

In [33]:
import math;
print("sqaure root",math.sqrt(9))
print("cos angle",math.cos(45))
math.pi

sqaure root 3.0
cos angle 0.5253219888177297


3.141592653589793

#Statitical functions like  Mean , Median and Standard Deviation

In [42]:
sv1 = np.array([1,4,5,3,6,78,3,22,6,8])
print("mean ", np.mean(sv1))
print("median ", np.median(sv1))
print("std deviation", np.std(sv1))
print("variance ",np.var(sv1))
print("max ", np.max(sv1))
print("min ", np.min(sv1))
print("logaritham  ", np.log(100))

mean  13.6
median  5.5
std deviation 22.168446043870556
variance  491.44000000000005
max  78
min  1
logaritham   4.605170185988092
